version: '2'
services:
  zipkin-demo-app:
    image: barrycommins/zipkindemoapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DOCKER_HOST_IP=$DOCKER_HOST_IP
  zipkin-server:
    image: barrycommins/zipkinserver
    ports:
      - "9411:9411"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DOCKER_HOST_IP=$DOCKER_HOST_IP

  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:3.0.1
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$DOCKER_HOST_IP:9092
      - KAFKA_ADVERTISED_HOST_NAME=$DOCKER_HOST_IP
      - KAFKA_CREATE_TOPICS="sleuth:1:1"